---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-state-metrics
spec:
  releaseName: kube-state-metrics
  chart:
    spec:
      chart: kube-state-metrics
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      version: "5.14.0"
  interval: 1h0m0s
  install:
    crds: CreateReplace
    remediation:
      retries: 3
    timeout: 10m
  upgrade:
    crds: CreateReplace
  valuesFrom:
  - name: flux-custom-metrics
