---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-monitoring-custom-metrics
spec:
  interval: 30m
  timeout: 2m0s
  targetNamespace: flux-system
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: "./k8s/flux-monitoring/dev/custom-metrics"
  prune: true
