---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
spec:
  values:
    defaultRules:
      additionalRuleLabels:
        cluster: doks-dev
      ingress:
        hosts:
        - alertmanager.mattera.io
      alertmanagerSpec:
        externalUrl: https://alertmanager.mattera.io
        storage:
          volumeClaimTemplate:
            spec:
              storageClassName: do-block-storage
    alertmanager:
      serviceMonitor:
        metricRelabelings:
        - targetLabel: cluster
          replacement: doks-dev
    grafana:
      serviceMonitor:
        metricRelabelings:
        - targetLabel: cluster
          replacement: doks-dev
    kubelet:
      serviceMonitor:
        metricRelabelings:
        - targetLabel: cluster
          replacement: doks-dev
        cAdvisorMetricsRelabelings:
        - targetLabel: cluster
          replacement: doks-dev
        probesMetricsRelabelings:
        - targetLabel: cluster
          replacement: doks-dev
        resourceMetricsRelabelings:
        - targetLabel: cluster
          replacement: doks-dev
    coreDns:
      serviceMonitor:
        metricRelabelings:
        - targetLabel: cluster
          replacement: doks-dev
    kube-state-metrics:
      prometheus:
        monitor:
          metricRelabelings:
          - targetLabel: cluster
            replacement: doks-dev
    prometheus-node-exporter:
      prometheus:
        monitor:
          metricRelabelings:
          - targetLabel: cluster
            replacement: doks-dev
    prometheusOperator:
      serviceMonitor:
        metricRelabelings:
        - targetLabel: cluster
          replacement: doks-dev
    prometheus:
      serviceMonitor:
        metricRelabelings:
        - targetLabel: cluster
          replacement: doks-dev
      ingress:
        hosts:
        - prometheus.mattera.io
      prometheusSpec:
        externalUrl: https://prometheus.mattera.io
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: do-block-storage
