---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
spec:
  values:
    defaultRules:
      additionalRuleLabels:
        cluster: doks-dev
      ingress:
        hosts:
        - alertmanager.mattera.io
      alertmanagerSpec:
        externalUrl: https://alertmanager.mattera.io
        storage:
          volumeClaimTemplate:
            spec:
              storageClassName: do-block-storage
    # working
    alertmanager:
      serviceMonitor:
        metricRelabelings:
        - targetLabel: cluster
          replacement: doks-dev
          sourceLabels: [__address__]
    # not working
    grafana:
      serviceMonitor:
        metricRelabelings:
        - targetLabel: cluster
          replacement: doks-dev
          sourceLabels: [__address__]
    kubelet:
      serviceMonitor:
        # working @ /metrics
        metricRelabelings:
        - targetLabel: cluster
          replacement: doks-dev
          sourceLabels: [__address__]
        # not working @ /metrics/cadvisor
        cAdvisorMetricsRelabelings:
        - targetLabel: cluster
          replacement: doks-dev
          sourceLabels: [__address__]
        probesMetricsRelabelings:
        - targetLabel: cluster
          replacement: doks-dev
          sourceLabels: [__address__]
        resourceMetricsRelabelings:
        - targetLabel: cluster
          replacement: doks-dev
          sourceLabels: [__address__]
    # working
    coreDns:
      serviceMonitor:
        metricRelabelings:
        - targetLabel: cluster
          replacement: doks-dev
          sourceLabels: [__address__]
    # working
    kube-state-metrics:
      prometheus:
        monitor:
          metricRelabelings:
          - targetLabel: cluster
            replacement: doks-dev
            sourceLabels: [__address__]
    # working
    prometheus-node-exporter:
      prometheus:
        monitor:
          metricRelabelings:
          - targetLabel: cluster
            replacement: doks-dev
            sourceLabels: [__address__]
    # working
    prometheusOperator:
      serviceMonitor:
        metricRelabelings:
        - targetLabel: cluster
          replacement: doks-dev
          sourceLabels: [__address__]
    # working
    prometheus:
      serviceMonitor:
        metricRelabelings:
        - targetLabel: cluster
          replacement: doks-dev
          sourceLabels: [__address__]
      ingress:
        hosts:
        - prometheus.mattera.io
      prometheusSpec:
        externalUrl: https://prometheus.mattera.io
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: do-block-storage
