---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana-agent-operator
  namespace: default
spec:
  values:
    resources:
      limits:
        memory: 256Mi
      requests:
        memory: 256Mi
        cpu: 100m
