apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
spec:
  releaseName: loki
  values:
    promtail:
      rbac:
        pspEnabled: false
    loki:
      rbac:
        pspEnabled: false
      structuredConfig:
        tableManager:
          retention_period: 72h
          retention_deletes_enabled: true
