apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - issuer-acme.yaml

# # need a git compliant way of storing this secret
# # using a manual secret
# secretGenerator:
#   - name: digitalocean-dns
#     envs:
#       - .env.do-token
