apiVersion: v1
data:
    digitalocean_api_token: ENC[AES256_GCM,data:zgU2mItT86RLdLGE2HAH0S7uDA5/cBALiJvJ73o3vW9272Wfg2BzJL2ty8X+ao7Jj4tcYlWUi8Mibhm7hc+dWBwUwpH1XaHE2RXhwt+/Fd43LXGDsW3iErwwQZWUYY7F,iv:iUuzF8a8ggwZ8LOjQ5l5YSJjVKyA8IohkKhpMKCJrpE=,tag:/RyLwmr3BjUUWzx6uI544g==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: digitalocean-token
    namespace: default
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault:
        - vault_address: https://vault.mattera.io:8200
          engine_path: sops
          key_name: firstkey
          created_at: "2023-09-07T18:38:51Z"
          enc: vault:v1:iyJtWjCRno3iGPUvWSSoY0rZxN4Eyllwr8kaE4SDiQkczKnSEg/2aaW/53p2G3pLjFmoXv3TZlklBSL2uP5fzBCu2NWw0349ywUblzAG8sDtmGIG+3q6l00/wTI3RRv/NG3/GxfqR6VWDjrM7aqN81YNIhE6Y8YICH10nSUsbkuomJlNO68kL8FZ+uQn6GYWSffjO8Lgxa5kc2NZcaLLBEkQdy0bq03KxvxqFZYWFWjswgS4uurV/kELHkLMIDiLZtdlevIcrIpFvVpQjGTHiM9jaIQhzkFprD7QkgQtTCg7EG5K5CehUyPES4Nfv704MMFrrPTsw/wwltwbCJGnxruZ0jbYXgfUptxx2lTdBwKfuVXtwwGBwkJ9Iil04X3SxY5OeaDPloCf3UgA3AatrBvA0ZhW171bUeX8uSlFmgROZuYJNiABTZAy2ADQW+N197fRr6XHqrj4IoJuZR3Bbtdn1sRgmQ5SDMHBcxkxxuqbDdliWXNkmbXb6TRvyNUJusmcm/jsMkFUUI/q6wpsQmJLNxXZ6WYXI8SCRscN7/S9FIVwcodLifea723PPMDwpoK8Kh8iDhtCPhx5AUj909y4oUyucy/hBRFGp5ECV/vm4AW+rbH0c4ae/g3GYJHiIrp8JQJFGSct2nJWL8cbof+9rlneoC2NIK1J9tFiK8Y=
    age: []
    lastmodified: "2023-09-07T18:38:51Z"
    mac: ENC[AES256_GCM,data:c63XE58nBeCtSZ4VR3yKzv0d+8lGRKTvypUaTUy7Vq6Job6IbX9sfNJXQcKasbYAuZu13xcAferzZ8S4KAQ+d4V5YayOL72/WgPIlQ03jXeK84mYNqmPXR6SQlCfqVRGa1f7jRU0JdY/9fACRa2IjRZ7MURY3zngL38WuJqgRNY=,iv:XmgGljJg2cifj9hunieFXzN4M+cc542XgzjM/JPe7Mw=,tag:DDMLGLCTE/ogcCCvqJWm2A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
