---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-mattera-io
spec:
  provider:
    vault:
      server: "https://vault.mattera.io:8200"
      auth:
        appRole:
          path: "approle"
          roleId: "role-id"
        secretRef:
          name: "vault-approle-external-secrets"
          key: "vault-token"
  conditions:
  - namespaceSelector:
      matchLabels:
        mattera.io/clustersecretstore: "true"
  - namespaces:
    - external-secrets
    - flux-system
