---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault
spec:
  provider:
    vault:
      server: "https://vault.mattera.io:8200"
      path: "kv"
      auth:
        appRole:
          path: "approle"
          roleId: "the-id"
        secretRef:
          name: "vault-approle-external-secrets"
          key: "vault-token"
  conditions:
    - namespaceSelector:
        matchLabels:
          mattera.io/clustersecretstore: "true"
    - namespaces:
        - external-secrets
        - flux-system
