---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-mattera-io
spec:
  provider:
    vault:
      server: "https://vault.mattera.io:8200"
      path: "kv"
      auth:
        appRole:
          roleRef:
            name: "vault-approle-external-secrets"
            namespace: "external-secrets"
            key: "role_id"
          secretRef:
            name: "vault-approle-external-secrets"
            namespace: "external-secrets"
            key: "secret_id"
  conditions:
  - namespaceSelector:
      matchLabels:
        mattera.io/clustersecretstore: "true"
  - namespaces:
    - external-secrets
    - flux-system
