---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: digitalocean-token
spec:
  dataFrom:
  - extract:
      key: digitalocean/clusters/doks-dev/cert-manager/dns-issuer-token
      version: latest
