---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-monitoring-controllers
spec:
  interval: 30m
  timeout: 2m0s
  targetNamespace: flux-system
  sourceRef:
    kind: GitRepository
    name: fluxcd-flux2-monitoring-example
  path: "./monitoring/controllers"
  prune: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-monitoring-configs
spec:
  interval: 30m
  timeout: 2m0s
  targetNamespace: flux-system
  dependsOn:
  - name: flux-monitoring-controllers
  sourceRef:
    kind: GitRepository
    name: fluxcd-flux2-monitoring-example
  path: "./monitoring/configs"
  prune: true
