---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
spec:
  chart:
    spec:
      # this is the version prior to a release that breaks the alert "explore" functionality
      version: "6.58.9"
  values:
    resources:
      limits:
        memory: 1Gi
      requests:
        cpu: 1
        memory: 512Mi
    # plugins:
    # - netsage-sankey-panel
    # - grafana-polystat-panel
    # - petrslavotinek-carpetplot-panel
    sidecar:
      alerts:
        enabled: true
        searchNamespace: ALL
      dashboards:
        enabled: true
        searchNamespace: ALL
      datasources:
        enabled: true
        searchNamespace: ALL
      plugins:
        enabled: true
        searchNamespace: grafana
      notifiers:
        enabled: true
        searchNamespace: ALL
    ingress:
      enabled: true
      annotations:
        ingress.pomerium.io/policy: |
          allow:
            and:
              - user:
                  is: haggishunk
        ingress.pomerium.io/pass_identity_headers: 'true'
        kubernetes.io/ingress.class: pomerium
      hosts:
      - grafana.mattera.io
      path: /
      pathType: Prefix
    serviceMonitor:
      enabled: true
      labels:
        mattera.io/monitoring: "true"
    persistence:
      enabled: true
      existingClaim: grafana-storage # hooks pod volumes to `storage` pvc created by sts volumeClaimTemplates
    useStatefulSet: true # make sure to use existingClaim matching hard-coded name `storage`
    grafana.ini:
      server:
        domain: mattera.io
        root_url: https://grafana.mattera.io/
      users:
        allow_sign_up: True
        viewers_can_edit: False
        editors_can_admin: False
      auth:
        disable_login_form: False
        disable_signout_menu: False
