---
apiVersion: monitoring.grafana.com/v1alpha1
kind: GrafanaAgent
metadata:
  name: grafana-agent
  namespace: default
  labels:
    app.kubernetes.io/component: agent
    app.kubernetes.io/name: grafana-agent
    app.kubernetes.io/part-of: grafana-agent
spec:
  logs:
    clients:
    - url: http://loki-gateway/loki/api/v1/push
      tenantId: anonymous
      externalLabels: {}
  metrics:
    externalLabels: {}
    remoteWrite:
    - url: http://mimir-nginx/api/v1/push
      headers:
        X-Scope-OrgID: anonymous
  serviceAccountName: grafana-agent
  resources:
    requests: {}
    limits: {}
