---
apiVersion: monitoring.grafana.com/v1alpha1
kind: GrafanaAgent
metadata:
  name: grafana-agent
  namespace: default
  labels:
    app.kubernetes.io/component: agent
    app.kubernetes.io/name: grafana-agent
    app.kubernetes.io/part-of: grafana-agent
spec:
  serviceAccountName: grafana-agent
