---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: grafana-agent
  labels:
    app.kubernetes.io/component: agent
    app.kubernetes.io/name: grafana-agent
    app.kubernetes.io/part-of: grafana-agent
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - nodes/proxy
  - nodes/metrics
  - services
  - endpoints
  - pods
  - events
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
- nonResourceURLs:
  - /metrics
  - /metrics/cadvisor
  verbs:
  - get
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana-agent
  namespace: default
  labels:
    app.kubernetes.io/component: agent
    app.kubernetes.io/name: grafana-agent
    app.kubernetes.io/part-of: grafana-agent
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: grafana-agent
  labels:
    app.kubernetes.io/component: agent
    app.kubernetes.io/name: grafana-agent
    app.kubernetes.io/part-of: grafana-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: grafana-agent
subjects:
- kind: ServiceAccount
  name: grafana-agent
  namespace: default
