---
apiVersion: monitoring.grafana.com/v1alpha1
kind: PodLogs
metadata:
  name: grafana-agent
  labels:
    app.kubernetes.io/component: logs
    app.kubernetes.io/name: grafana-agent-meta-monitoring
    app.kubernetes.io/part-of: grafana-agent
spec:
  jobLabel: app.kubernetes.io/name
  pipelineStages:
  - cri: {}
  relabelings:
  - action: replace
    replacement: $1
    separator: /
    sourceLabels:
    - __meta_kubernetes_namespace
    - __meta_kubernetes_pod_container_name
    targetLabel: job
  - action: replace
    sourceLabels:
    - __meta_kubernetes_pod_container_name
    targetLabel: name
