---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: grafana-agent
  labels:
    mattera.io/grafana-agent: infrastructure
spec:
  jobLabel: app.kubernetes.io/name
  podMetricsEndpoints:
  - enableHttp2: false
    filterRunning: true
    followRedirects: false
    honorLabels: true
    honorTimestamps: true
    metricRelabelings: []
    path: /metrics
    port: http-metrics
    scheme: http
  selector:
    matchLabels:
      app.kubernetes.io/name: grafana-agent
