---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: grafana-agent
  labels:
    app.kubernetes.io/component: metrics
    app.kubernetes.io/name: grafana-agent-meta-monitoring
    app.kubernetes.io/part-of: grafana-agent
spec:
  jobLabel: app.kubernetes.io/name
  podMetricsEndpoints:
  - followRedirects: false
    honorLabels: true
    honorTimestamps: true
    metricRelabelings: []
    path: /metrics
    port: http-metrics
    scheme: http
