---
apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Alert
metadata:
  name: error
spec:
  summary: "Flux error"
  providerRef:
    name: error
  eventMetadata:
    severity: error
  eventSeverity: error
  eventSources:
  - kind: GitRepository
    name: '*'
  - kind: Kustomization
    name: '*'
  - kind: HelmChart
    name: '*'
  - kind: HelmRelease
    name: '*'
  - kind: HelmRepository
    name: '*'
  exclusionList:
  - "waiting.*socket"
