---
apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Alert
metadata:
  name: info
spec:
  summary: "Flux update"
  providerRef:
    name: info
  eventMetadata:
    severity: info
  eventSeverity: info
  eventSources:
  - kind: Kustomization
    name: '*'
  - kind: HelmRelease
    name: '*'
  inclusionList:
  - "(configured|created|deleted)"
