apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: flux-provider-secret
spec:
  dataFrom:
  - extract:
      key: flux-provider-secret
      version: latest
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gsm
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
