---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
spec:
  releaseName: loki
  dependsOn:
  - name: kube-prometheus-stack
  chart:
    spec:
      chart: loki
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      version: ">=5.0.0 <6.0.0"
  interval: 1h0m0s
  install:
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
  values:
    tableManager:
      retention_deletes_enabled: true
      retention_period: 7d
    write:
      replicas: 1
    read:
      replicas: 1
    backend:
      replicas: 1
    singleBinary:
      replicas: 1
    gateway:
      replicas: 1
    serviceMonitor:
      metricsInstance:
        enabled: false
    monitoring:
      selfMonitoring:
        enabled: false
