---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-admin-credentials
spec:
  refreshInterval: "30m"
  dataFrom:
  - extract:
      key: digitalocean/clusters/doks-dev/grafana/admin-credentials
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-mattera-io
