---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
spec:
  chart:
    spec:
      version: ">=6.0.0 <7.0.0"
  install:
    timeout: 15m
  values:
    resources:
      limits:
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 512Mi
    admin:
      existingSecret: grafana-admin-password
    #   userKey: admin-user
    #   passwordKey: admin-password
