---
apiVersion: ingress.pomerium.io/v1
kind: Pomerium
metadata:
  name: global
  namespace: default
spec:
  secrets: pomerium/bootstrap
  authenticate:
    url: https://authenticate.pomerium.app
  certificates:
  - pomerium/pomerium-wildcard-tls
