---
apiVersion: ingress.pomerium.io/v1
kind: Pomerium
metadata:
  name: global
  namespace: default
spec:
  secrets: pomerium/bootstrap
  authenticate:
    url: https://authenticate.mattera.io
  certificates:
  - pomerium/pomerium-wildcard-tls
  identityProvider:
    provider: github
    secret: pomerium/github-oauth-credentials
