apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
spec:
  values:
    serviceMonitor:
      enabled: true
    provider: digitalocean
    domainFilters:
      - mattera.io
    env:
      name: DO_TOKEN
      valueFrom:
        secretRef:
          name: digitalocean-dns
          key: token
