apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
spec:
  values:
    provider: digitalocean
    digitalocean:
      secretName: digitalocean-dns
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    domainFilters:
      - mattera.io
