apiVersion: v1
data:
    digitalocean_api_token: ENC[AES256_GCM,data:aVDj8IRbUpB0g6iFgihN5NwpWL0mspqxi1w0CUA7dULHNjeC9MsBuWYEcFM9gqywyDErhOBEm9epCW9ViGP09aR76VcsoSblphCXdoo9cZ18fSO+CKYWuJ56mKKstYEY,iv:Z6qj4i7u9TtWlW9e6A1lh1Hyrz1RSQEkETOOLB47HNc=,tag:yrZPDv/VOPOYK1hW2tLpVg==,type:str]
kind: Secret
metadata:
    name: digitalocean-dns
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault:
        - vault_address: https://vault.mattera.io:8200
          engine_path: sops
          key_name: firstkey
          created_at: "2023-03-23T04:31:33Z"
          enc: vault:v1:pIRF6qeSG6om3ehccqzBipX51zqrJukaiEbh26ajUJ7bbYQ6priTo6iv8EofTF9m376UoOtbe3w62jrpR3p7tZVGQR/DP8fRVeLq03NfwPrL+o+BfZe9R8Qxj7g3W0clto9nny31JWSG4b9/m190Y87NKtgfEvq/e8BYA+H0NUApQ0pUes9M5dZ6OHNbfSb9p8f57776ibh0MpaZwqp7FtiyB9Be3Wl5v0iVfYhdesNGKYgbsLkdUx/vL7lcE8sh7aTd6uXMrckOou+iQJ3PPoip0CVqlpJlv8upiMS06IbagBsKFitDHnIQSEwtJczYKp7/TOX9TadpuGn9ZhEePhbDiuL5V11jdZuLJ2FYrLVyWXx3Nr+gypwuDKdSifOwzegJmhurnz1qey8d4J9C9h0sR08MmcCnM6bBAMhFVyBz6sq0r0XBnsnC6PgbPjqLJKFNyw99VfMHyX3H15ajc4AMunWMbbX3/KtX5mUF4A8kB+OPrRtxggD+XaugFTPokIC3GviJNuO7xrUpMk+LFxr3nZ/B3l045g5aJ9vzjuTS7eeLE//aEM38KgOYbNKwFQjQBo05bgHxSh2uarW8prKRv+6AG53mfLzhoUs45863yNdpvhUcaMkJh1nR2UklfY5Bp/kV/fSrO328TROY1Ke9SYm0UaJRB6z18zHQow4=
    age: []
    lastmodified: "2023-03-23T04:31:33Z"
    mac: ENC[AES256_GCM,data:qoyYeCrGv7b6qHH0oMHiqA7kSFJL5HB1ovWijrhOpmpAgYQ7xrcmC8uuPPgCN8TVq6Lef0i0y4qVJmEEGLaVd79z0iLWun+KUjG2Ueaq5ztAmYNBkcAfN/fsdIUxRobSvdceukX1oNVUXzTJwRhNIypvqaNJpCbXSWJrKoHU4Jo=,iv:kYkJYPQt3PX+BogBB7qb563fw/GTcA389Gr8rGXB+7Q=,tag:FHSyQh7XW9gbi5ZzBSZNZw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
