apiVersion: v1
data:
    digitalocean_api_token: ENC[AES256_GCM,data:OoqjulDXwey4cFrxe8qya37g1t61o1cfxMEjMPjUyxxE1IndghQATfCVpK3uTyh7yBijHhlN6awflCy+w9U9Ph0wm4o9sYyHT0PImuz3vbWwyzz29M0WyLswN0Fa0RCN,iv:p+/SdrC0QulOI2xT3NHGHsMGDlg8t7h7zErdbrONRUU=,tag:PZSJuoKEx8CocQ949jaH5w==,type:str]
kind: Secret
metadata:
    name: digitalocean-dns
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault:
        - vault_address: https://vault.mattera.io:8200
          engine_path: sops
          key_name: firstkey
          created_at: "2023-03-16T05:09:27Z"
          enc: vault:v1:Y9QUtHBCyswCP8JgGmK94vDb6BNzUFvZf9rynG6e7y/lHzRmnrI0g2SUpW0XPsYj/YcALXJk2LwTFH8gM0Gk/v1Mivwg7cbJXgA9HYJcP+mavG4/dZw/oQ5OibxIpiXSZTTkS2lriFx96ETuxkmvvitLa3vwzqhuNfOLsa+xGIQr5r7Z1KbPf5i+/h0trmFxg7tCt1r6ZFtZ7CTNGA7L8+GPST7205duUh4Bfe5ADTZhOFeVMzDuIe+lJdfWqBLPf+Gi31x9ZeRmhlFjfYuU3DyFmIOMUA3+KpCe1HtsA3T+3xht2LFUa2Xs/bb3lhxm9fdjgUKNqPiML61lxZhDbAymxOFI9Rh5CuFRU4VatQTT7E39t9TaOoRPBIukhHoLSFx9G19MExF2BAbRNKwPMFGfu+btaZD7XKx4THh/NpV4YnfE4pI5oGHu7uGXzE+Roazr6swNZ/3j4gpwBARxV9yqD4a0VklL0VePYLb2i/3VhmnlB9AS1/mIk5UwE2fYUkmB7JYFK1WKEj/RyIErOczyGrrVsTMDL65UO/toE8iIacHudtLk5YcQJ2TjiaWwIZf540Rrs0FiXe1Sjv9x/10Uw0b9JYJTFNgCrCXmM+HZ3QzY2gYxcylQQARneBcdlEc9AcHI+G4gDJk09yIX6+iFMIz93n5EptRNw2iX1Xo=
    age: []
    lastmodified: "2023-03-16T05:09:28Z"
    mac: ENC[AES256_GCM,data:6ZPmFB32H/9xQJFfgJ+MMIGsX3TEBm1r4NYe7HbbdhlcxBrBi8XFR+EWJxiVpNTjKzmCD9nCB59B0Ua7UZlxJbwYAvsp1GRJ5m8KBzE96XL6xcKbvaSj/TFD3mF19mPNH6eMKdA+51wqFpxRuX37nk/sMQ3qtk3HBFigp/vM8mA=,iv:Pc4VxeY50/StB7YHhtzIBIS0KDFo190mBzxMYgh1W2U=,tag:/UJewh6KuJz+/GoJiGpOyA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
