apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
namePrefix: gorgeous-
nameSuffix: -general
resources:
- ../../../../base/flux-notifications/slack
patches:
- patch: |
    - op: add
      path: /spec/channel
      value: test-flux-notifications
      create: true
  target:
    group: notification.toolkit.fluxcd.io
    kind: Provider
    version: v1beta2
- patch: |
    - op: add
      path: /spec/eventMetadata/cluster
      value: gorgeous
      create: true
  target:
    group: notification.toolkit.fluxcd.io
    kind: Alert
