apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-secrets
resources:
- ../../../base/external-secrets
- sops-secret.yaml
# source secrets from a particular gcp project
patches:
- patch: |
    - op: replace
      path: /spec/provider/vault/auth/roleId
      value: d15d632c-5741-a07b-82fb-a5678c5157a5
  target:
    kind: ClusterSecretStore
    name: vault
