apiVersion: v1
data:
    vault-token: ENC[AES256_GCM,data:63hMNkFqQivRkVdUuhGywwvt7PVTmzJU4OZfQGxRuJdbRyeCli9n0bgzPDOlqJoK,iv:8eTbZLfyYA2mJwqBqHeZhzjP/SxhzB2b+0IXFPgtx2s=,tag:b10M1cp3VBzhDvq1uV120g==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: vault-approle-external-secrets
    namespace: default
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault:
        - vault_address: https://vault.mattera.io:8200
          engine_path: sops
          key_name: firstkey
          created_at: "2023-09-07T20:15:10Z"
          enc: vault:v1:y6e/eo6sCJsVpq9WM4ODQdwlk+OU3ve2YRkz4P2U/lta7Oi99zSjHWYuQk+PJFBFvpjQYXJDBCPBXatF7WFGgwHcpoKcNfajjbIlLCC695wupfXtgy4gIhkCLDyKGYA+fZBucD+qiVfc9Gxojt9HROipyS/yIqFSTV39MQ6SyWE5Ey9YHVMCtRrt4yZcqtiC7O3Da4yDM5TdPZECuxl+qDP8b8OfqRP8MbBnIKdycPlgJdNcwPxGq6bduRdNdrmv7gtA3yshroFAJHz21siVK5+Co6kxcuApHcG7+I9Vvwtjb9kHoc3jsIYpMpZhoSfAxCryA0P8j/qmFUiJUs/o2DF2Hwl8Ludtk71hjEGVRVxDr96I6YgGrZuWctBLxezNd10fj3mrjUyJOiDKCab5Wv9w7snkpBI0Tsl0e1+9julR/aNAAaJjPO7Dc1pGLYl8Ns8vXfg15Y44lYZP7pW+f72ksN/h0e+yCKslsVy+sVb3D7dHF/SjgzSkUj8XIMjxa7ezAlJXuxln+XujMAAbnXDAtQS9iYKh6qBCk5VnxBFl9A+X3v0cFs8XOfxHxNaqBVsJLVmTY5DBVsQQZ7xdVynTu0+e+iYOVkP7tb7jaZlRWv94GhZqR4k/UFEORW6tJcv+IIxD0BIpnIt7onPBWCZPkCQPz2wn6r15PnQXmVI=
    age: []
    lastmodified: "2023-09-07T20:15:10Z"
    mac: ENC[AES256_GCM,data:5c1aYsQK3qi83TYvvtzVy7aBrn6N118tAl6+LMjFfdgMt3eIx9yOYbbgIBZQ5ejr841mIBm5ljO+b0EeLqyQYLMFkuy5TZYcPJs0mX5HS6w8kLSiyzInTEfWkEFXwRDp7MGThYNCaFFqP0FUP9vsoFGlV2Qshao56WvblF/0XZA=,iv:SxUAYmW1laiLcDpHKzAYO8fHTjtX0qxUeaAA1E7xT+A=,tag:a9HvwWGSKR1CKB00k1REzQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
