---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: s3-bucket-credentials
spec:
  dataFrom:
  - extract:
      key: path/to/key
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-mattera-io
