---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cert-manager-issuer
  namespace: cert-manager
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
  - name: cert-manager
  path: k8s/infrastructure/cert-manager/dev
  prune: true
  patches:
  - patch: |
      - op: replace
        path: /spec/dataFrom/0/extract/key
        value: digitalocean/clusters/doks-dev/cert-manager/dns-issuer-token
    target:
      kind: ExternalSecret
      group: external-secrets.io
      name: digitalocean-token
