---
apiVersion: v1
kind: Namespace
metadata:
  name: external-dns
  labels:
    mattera.io/clustersecretstore: "true"
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: external-dns
  namespace: external-dns
spec:
  targetNamespace: external-dns
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: k8s/infrastructure/external-dns/dev
  prune: true
