---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: external-secrets-store
  namespace: external-secrets
spec:
  targetNamespace: external-secrets
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
  - name: external-secrets
    namespace: external-secrets
  path: k8s/infrastructure/external-secrets-store/dev
  prune: true
  patches:
  - patch: |
      - op: replace
        path: /spec/provider/vault/path
        value: kv
    target:
      kind: ClusterSecretStore
      name: vault
