---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-monitoring
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: fluxcd-flux2-monitoring-example
  dependsOn:
  - name: kube-prometheus-stack
  path: monitoring/config
  prune: true
