---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-monitoring-custom-metrics
  namespace: monitoring
spec:
  interval: 30m
  timeout: 2m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
  - name: kube-prometheus-stack
  path: k8s/infrastructure/flux-monitoring/dev
  prune: true
