---
apiVersion: v1
kind: Namespace
metadata:
  name: grafana
  labels:
    mattera.io/clustersecretstore: "true"
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: grafana
  namespace: grafana
spec:
  targetNamespace: grafana
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: k8s/infrastructure/grafana/dev
  prune: true
