---
apiVersion: v1
kind: Namespace
metadata:
  name: grafana-operator
  labels:
    mattera.io/clustersecretstore: "true"
    mattera.io/monitor: "true"
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: grafana-operator
  namespace: grafana-operator
spec:
  targetNamespace: grafana-operator
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system-dev
    namespace: flux-system
  path: k8s/infrastructure/grafana-operator/dev
  prune: true
