---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    mattera.io/clustersecretstore: "true"
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  targetNamespace: monitoring
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: k8s/infrastructure/kube-prometheus-stack/dev
  prune: true
