---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: mimir
  namespace: monitoring
spec:
  targetNamespace: monitoring
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system-dev
    namespace: flux-system
  dependsOn:
  - name: kube-prometheus-stack
    namespace: monitoring
  path: k8s/infrastructure/mimir/dev
  prune: true
  patches:
  - patch: |
      - op: replace
        path: /spec/dataFrom/0/extract/key
        value: digitalocean/clusters/doks-dev/do-spaces-credentials
    target:
      kind: ExternalSecret
      name: s3-bucket-credentials
