---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: pomerium-monitoring
  namespace: pomerium
spec:
  targetNamespace: pomerium
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: pomerium-ingress-controller
    namespace: flux-system
  dependsOn:
  - name: pomerium-ingress-controller
    namespace: pomerium
  path: config/prometheus
  prune: true
