---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: pomerium-ingress
  namespace: pomerium
spec:
  targetNamespace: pomerium
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system-dev
    namespace: flux-system
  dependsOn:
  - name: pomerium-ingress-controller
    namespace: pomerium
  path: k8s/infrastructure/pomerium-ingress/dev
  prune: true
