---
apiVersion: v1
kind: Namespace
metadata:
  name: pomerium
  labels:
    mattera.io/clustersecretstore: "true"
    mattera.io/monitor: "true"
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: pomerium-ingress-controller
  namespace: pomerium
spec:
  targetNamespace: pomerium
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: pomerium-ingress-controller
    namespace: flux-system
  path: config/default
  components:
  - ../components/prometheus
  prune: true
  patches:
  - patch: |
      - op: add
        path: /metadata/annotations/service.beta.kubernetes.io~1do-loadbalancer-protocol
        value: "http"
      - op: add
        path: /metadata/annotations/service.beta.kubernetes.io~1do-loadbalancer-tls-ports
        value: "443"
      - op: add
        path: /metadata/annotations/service.beta.kubernetes.io~1do-loadbalancer-redirect-http-to-https
        value: "true"
      - op: add
        path: /metadata/annotations/external-dns.alpha.kubernetes.io~1hostname
        value: "authenticate.mattera.io"
    target:
      kind: Service
      name: pomerium-proxy
  - patch: |
      - op: add
        path: /metadata/labels/mattera.io~1monitor
        value: "true"
    target:
      kind: ServiceMonitor
