---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: pomerium-ingress-controller
  namespace: pomerium
spec:
  targetNamespace: pomerium
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: pomerium-ingress-controller
    namespace: flux-system
  path: config/default
  prune: true
