---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: promtail
  namespace: monitoring
spec:
  targetNamespace: monitoring
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system-dev
    namespace: flux-system
  dependsOn:
  - name: kube-prometheus-stack
    namespace: monitoring
  path: k8s/infrastructure/promtail/dev
  prune: true
