---
apiVersion: v1
kind: Namespace
metadata:
  name: ssh
  labels:
    mattera.io/clustersecretstore: "true"
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: ssh-server
  namespace: ssh
spec:
  targetNamespace: ssh
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system-dev
    namespace: flux-system
  path: k8s/infrastructure/ssh-server/base
  prune: true
