apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
spec:
  values:
    grafana:
      ingress:
        enabled: true
        ingressClassName: traefik
        hosts:
          - grafana.mattera.io
        annotations:
          external-dns.alpha.kubernetes.io/hostname: grafana.mattera.io
          cert-manager.io/cluster-issuer: letsencrypt-acme-digitalocean
        tls:
          - secretName: kube-prometheus-stack-grafana-tls
            hosts:
              - grafana.mattera.io

      serviceMonitor:
        enabled: true
