apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
spec:
  values:
    coreDns:
      enabled: true
    prometheusOperator:
      resources:
        limits:
          memory: 50Mi
        requests:
          cpu: 100m
          memory: 50Mi
    prometheus:
      prometheusSpec:
        priorityClassName: infra-cluster-critical
        retention: 24h
        resources:
          limits:
            memory: 256Mi
          requests:
            cpu: 200m
            memory: 128Mi
        podMonitorSelectorNilUsesHelmValues: false
        podMonitorNamespaceSelector: {}
        podMonitorSelector: {}
        serviceMonitorSelectorNilUsesHelmValues: false
        serviceMonitorSelector: {}
        ruleSelectorNilUsesHelmValues: false
    grafana:
      ingress:
        enabled: true
        ingressClassName: traefik
        hosts:
          - grafana.mattera.io
      serviceMonitor:
        enabled: true
