apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: slack-bot-token
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: gsm
  target:
    name: slack-bot-token
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: slack-bot-token-test-flux
        version: latest
        property: token
