---
apiVersion: 1
datasources:
- name: Mimir
  type: prometheus
  uid: mimir
  url: http://mimir-nginx:8080/prometheus
  typeLogoUrl: public/app/plugins/datasource/prometheus/img/mimir_logo.svg
  access: proxy
  isDefault: false
  jsonData:
    timeInterval: 30s
    manageAlerts: true
    alertmanagerUid: mimir-alertmanager
    prometheusType: Mimir
    prometheusVersion: '2.4.0'
    httpMethod: GET
    httpHeaderName1: 'X-Scope-OrgID'
  secureJsonData:
    httpHeaderValue1: 'mattera-io'
