---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-secrets
spec:
  releaseName: external-secrets
  chart:
    spec:
      chart: external-secrets
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: flux-system
      version: "0.9.5"
  interval: 1h0m0s
  install:
    crds: CreateReplace
    remediation:
      retries: 3
    timeout: 10m
  upgrade:
    crds: CreateReplace
  # https://github.com/external-secrets/kubernetes-external-secrets/blob/master/charts/kubernetes-external-secrets/values.yaml
  values:
    installCRDs: false # manual management
    securityContext:
      runAsNonRoot: true
    resources:
      limits:
        cpu: 100m
        memory: 256Mi
      requests:
        cpu: 10m
        memory: 32Mi
    webhook:
      resources:
        limits:
          cpu: 50m
          memory: 256Mi
        requests:
          cpu: 10m
          memory: 32Mi
      lookaheadInterval: 24h
      certManager:
        enabled: true
        cert:
          issuerRef:
            group: cert-manager.io
            kind: Issuer
            name: external-secrets-ca
    certController:
      create: false # using cert manager instead
      resources:
        limits:
          cpu: 50m
          memory: 128Mi
        requests:
          cpu: 10m
          memory: 128Mi
