---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: promtail
spec:
  releaseName: promtail
  chart:
    spec:
      chart: promtail
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      version: ">=6.0.0 <7.0.0"
  interval: 1h0m0s
  install:
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
  values:
    resources:
      limits:
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
    serviceMonitor:
      enabled: true
      labels:
        mattera.io/monitor: "true"
    prometheusRule:
      enabled: true
      additionalLabels:
        mattera.io/monitor: "true"
    sidecar:
      configReloader:
        enabled: true
