---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: pomerium-ingress-controller
spec:
  interval: 300m0s
  ref:
    semver: ">=v0.23.0 <v0.24.0"
  timeout: 60s
  url: https://github.com/pomerium/ingress-controller.git
  recurseSubmodules: false
  include:
  - repository:
      name: pomerium-ingress-controller
    fromPath: config/config
    toPath: compose/mattera-io/config
  - repository:
      name: pomerium-ingress-controller
    fromPath: config/prometheus
    toPath: compose/mattera-io/prometheus
  ignore: |
    # exclude all
    /*
    # include manifests
    !/config
    !/compose/mattera-io
