---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: pomerium-ingress-controller
spec:
  interval: 300m0s
  ref:
    semver: ">=v0.23.0 <v0.24.0"
  timeout: 60s
  url: https://github.com/pomerium/ingress-controller.git
  recurseSubmodules: false
  include:
  # this is effectively `default` + `prometheus`
  - repository:
      name: pomerium-ingress-controller
    fromPath: config/crd
    toPath: config/mattera-io/crd
  - repository:
      name: pomerium-ingress-controller
    fromPath: config/pomerium
    toPath: config/mattera-io/pomerium
  - repository:
      name: pomerium-ingress-controller
    fromPath: config/gen_secrets
    toPath: config/mattera-io/gen_secrets
  - repository:
      name: pomerium-ingress-controller
    fromPath: config/default
    toPath: config/mattera-io/default
  - repository:
      name: pomerium-ingress-controller
    fromPath: config/prometheus
    toPath: config/mattera-io/default/prometheus
  ignore: |
    # exclude all
    /*
    # include manifests
    !/config
