apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
namePrefix: grafana-
resources:
- ../general
patches:
- patch: |
    - op: replace
      path: /spec/type
      value: grafana
    - op: add
      path: /spec/address
      value: http://grafana.grafana/api/annotations
      create: true
  target:
    group: notification.toolkit.fluxcd.io
    kind: Provider
    version: v1beta2
