---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
patches:
- patch: |
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests
      value:
        cpu: 100m
        memory: 128Mi
  target:
    kind: Deployment
    name: source-controller
- patch: |
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests
      value:
        cpu: 100m
        memory: 128Mi
  target:
    kind: Deployment
    name: helm-controller
