---
apiVersion: monitoring.grafana.com/v1alpha1
kind: MetricsInstance
metadata:
  name: metrics-instance
spec:
  minWALTime: 5m
  maxWALTime: 60m

  remoteWrite:
  - url: http://mimir-nginx/api/v1/push

  # Supply an empty namespace selector to look in all namespaces. Remove
  # this to only look in the same namespace as the MetricsInstance CR
  # serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector: {}

  # Supply an empty namespace selector to look in all namespaces. Remove
  # this to only look in the same namespace as the MetricsInstance CR.
  # podMonitorNamespaceSelector: {}
  podMonitorSelector: {}

  # Supply an empty namespace selector to look in all namespaces. Remove
  # this to only look in the same namespace as the MetricsInstance CR.
  # probeNamespaceSelector: {}
  probeSelector: {}
