apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-secrets
spec:
  values:
    installCRDs: true
    image:
      repository: haggishunk/external-secrets
      tag: v0.9.4-armv7
