---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
spec:
  releaseName: kube-prometheus-stack
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      version: ">=45.0.0 <46.0.0"
  interval: 1h0m0s
  install:
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
  values:
    coreDns:
      enabled: true
    prometheusOperator:
      resources:
        limits:
          memory: 64Mi
        requests:
          cpu: 50m
          memory: 64Mi
    alertmanager:
      alertmanagerSpec:
      resources:
        limits:
          memory: 128Mi
        requests:
          cpu: 50m
          memory: 128Mi
    prometheus:
      prometheusSpec:
        retention: 1d
        resources:
          limits:
            memory: 512Gi
          requests:
            cpu: 250m
            memory: 512Gi
        podMonitorSelectorNilUsesHelmValues: false
        podMonitorSelector: {}
        serviceMonitorSelectorNilUsesHelmValues: false
        serviceMonitorSelector: {}
        ruleSelectorNilUsesHelmValues: false
    # SUBCHART
    grafana:
      resources:
        limits:
          memory: 512Mi
        requests:
          cpu: 100m
          memory: 384Mi
      sidecar:
        alerts:
          enabled: true
          searchNamespace: ALL
        dashboards:
          enabled: true
          searchNamespace: ALL
        datasources:
          enabled: true
          searchNamespace: ALL
        plugins:
          enabled: true
          searchNamespace: ALL
