---
apiVersion: monitoring.grafana.com/v1alpha1
kind: PodLogs
metadata:
  name: logs
  namespace: default
spec:
  jobLabel: app.kubernetes.io/name
  pipelineStages:
  - cri: {}
  relabelings:
  - action: replace
    replacement: $1
    separator: /
    sourceLabels:
    - __meta_kubernetes_namespace
    - __meta_kubernetes_pod_container_name
    targetLabel: job
  - action: replace
    sourceLabels:
    - __meta_kubernetes_pod_container_name
    targetLabel: name
  selector:
    matchLabels: {}
