---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- release.yaml
configMapGenerator:
- name: flux-custom-metrics
  files:
  - values.yaml
configurations:
- kustomizeconfig.yaml
