---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: digitalocean-token
spec:
  dataFrom:
  - extract:
      key: path/to/key
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-mattera-io
