---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
spec:
  interval: 20m
  chart:
    spec:
      chart: external-dns
      version: '6.14.4'
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 30m
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
  values:
    provider: digitalocean
    digitalocean:
      # must have `digitalocean_api_token` key
      secretName: digitalocean-token
